import asyncio
import json
from collections.abc import AsyncIterator
from dataclasses import dataclass
from pathlib import Path

from corki.config import CorkiSettings
from corki.config.instructions import ProjectInstructionsConfig
from corki.core import LangGraphRuntime
from corki.models import ModelCompleted, ModelRequest, ModelTextDelta
from corki.models.types import ModelEvent
from corki.protocol.events import (
    AssistantTextDelta,
    PlanUpdated,
    ToolCallCompleted,
    TurnCompleted,
    TurnFailed,
)
from corki.protocol.ids import ToolCallId
from corki.protocol.items import AssistantMessageItem, ToolCallItem, UserMessageItem, new_step_id
from corki.protocol.tools import ToolCall


@dataclass(frozen=True)
class ScriptedStep:
    text: str = ""
    chunks: tuple[str, ...] = ()
    calls: tuple[tuple[str, str, dict[str, object]], ...] = ()


class ScriptedModel:
    def __init__(self, steps: list[ScriptedStep]) -> None:
        self.steps = steps
        self.requests: list[ModelRequest] = []
        self.closed = False

    async def stream(self, request: ModelRequest) -> AsyncIterator[ModelEvent]:
        self.requests.append(request)
        step = self.steps.pop(0)
        for chunk in step.chunks:
            yield ModelTextDelta(chunk)
        calls = tuple(
            ToolCall(
                ToolCallId(call_id),
                name,
                arguments,
                raw_arguments=json.dumps(arguments),
            )
            for call_id, name, arguments in step.calls
        )
        step_id = new_step_id()
        turn_id = request.items[-1].turn_id
        items = (
            *((AssistantMessageItem(step.text, turn_id, step_id),) if step.text else ()),
            *(ToolCallItem(call, turn_id, step_id) for call in calls),
        )
        yield ModelCompleted(items)

    async def aclose(self) -> None:
        self.closed = True


def test_langgraph_streams_and_recalls_complete_coding_loop(tmp_path: Path) -> None:
    model = ScriptedModel(
        [
            ScriptedStep(
                text="I will inspect and plan.",
                chunks=("I will ", "inspect and plan."),
                calls=(
                    (
                        "plan-1",
                        "update_plan",
                        {
                            "explanation": "Inspect before changing files.",
                            "plan": [
                                {"step": "inspect", "status": "in_progress"},
                                {"step": "implement", "status": "pending"},
                            ],
                        },
                    ),
                    ("exec-1", "exec_command", {"cmd": "printf observed"}),
                ),
            ),
            ScriptedStep(
                calls=(
                    (
                        "patch-1",
                        "apply_patch",
                        {
                            "patch": """*** Begin Patch
*** Add File: generated.txt
+generated by corki
*** End Patch"""
                        },
                    ),
                )
            ),
            ScriptedStep(
                calls=(
                    (
                        "verify-1",
                        "exec_command",
                        {"cmd": "test -f generated.txt && printf verified"},
                    ),
                )
            ),
            ScriptedStep(text="Done.", chunks=("Do", "ne.")),
            ScriptedStep(text="I remember the completed work.", chunks=("I remember",)),
        ]
    )
    settings = CorkiSettings(
        working_directory=tmp_path,
        project_instructions=ProjectInstructionsConfig(trust_level="trusted"),
        command_yield_seconds=1,
        command_timeout_seconds=3,
    )
    runtime = LangGraphRuntime.create(
        settings=settings,
        database_path=tmp_path / ".corki" / "sessions.db",
        model=model,
    )

    async def scenario() -> tuple[list[object], list[object]]:
        first = [event async for event in runtime.stream("create the generated file")]
        second = [event async for event in runtime.stream("what did you just complete?")]
        await runtime.aclose()
        return first, second

    first_events, second_events = asyncio.run(scenario())

    assert (tmp_path / "generated.txt").read_text() == "generated by corki\n"
    assert "".join(
        event.delta for event in first_events if isinstance(event, AssistantTextDelta)
    ).endswith("Done.")
    assert [event.explanation for event in first_events if isinstance(event, PlanUpdated)] == [
        "Inspect before changing files."
    ]
    assert sum(isinstance(event, ToolCallCompleted) for event in first_events) == 4
    assert isinstance(first_events[-1], TurnCompleted)
    assert isinstance(second_events[-1], TurnCompleted)
    assert len(model.requests) == 5
    assert any(
        item.content == "create the generated file"
        for item in model.requests[-1].items
        if isinstance(item, UserMessageItem)
    )
    assert model.closed


def test_evaluation_stops_excess_tool_calls_before_execution(tmp_path: Path) -> None:
    model = ScriptedModel(
        [
            ScriptedStep(
                calls=(
                    ("one", "exec_command", {"cmd": "touch one"}),
                    ("two", "exec_command", {"cmd": "touch two"}),
                )
            )
        ]
    )
    settings = CorkiSettings(working_directory=tmp_path, max_tool_calls=1)
    runtime = LangGraphRuntime.create(
        settings=settings,
        database_path=tmp_path / "limits.db",
        model=model,
    )

    async def scenario() -> list[object]:
        events = [event async for event in runtime.stream("do too much")]
        await runtime.aclose()
        return events

    events = asyncio.run(scenario())

    assert isinstance(events[-1], TurnFailed)
    assert "tool call limit" in events[-1].error
    assert not (tmp_path / "one").exists()
    assert not (tmp_path / "two").exists()
